name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  max_tokens:
    description: "Maximum number of tokens that can be generated per analysis."
    required: false
    default: "700"
  DELAY_BETWEEN_BATCHES:
    description: "Delay in milliseconds between sending the requests to GitHub API."
    required: false
    default: "2500"
  BATCH_SIZE:
    description: "Amount of comments to send as a bunch"
    required: false
    default: "5"
  include:
    description: "Glob patterns to include files for the diff analysis"
    required: false
    default: ""
  custom_prompts:
    description: "Custom commands to augment the agent's prompts with. Each line is an individual command."
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
